#!/bin/sh

sxhkd &

bspc monitor eDP1 -d I II III IV V VI VII VIII IX X
bspc monitor HDMI1 -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

$HOME/.scripts/random-wallpaper
$HOME/.config/polybar/launch.sh
