#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DisplayPort-1 -d I II III IV V VI VII VIII IX X
bspc monitor DisplayPort-0 -d I II III IV V VI VII VIII IX X
bspc monitor HDMI-A-0 -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# rules

bspc rule -a obsidian desktop=^12
bspc rule -a discord desktop=^11
bspc rule -a steam desktop=^30
bspc rule -a heroic desktop=^29

$HOME/.config/polybar/launch.sh
$HOME/.scripts/random-wallpaper
$HOME/.scripts/setup-details
