#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-0 -d I II III IV V VI VII VIII IX X
bspc monitor DP-0 -d I II III IV V VI VII VIII IX X
bspc monitor DVI-D-0 -d I II III IV V VI VII VIII IX X
bspc monitor Virtual-1 -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

$HOME/.config/polybar/launch.sh
$HOME/.scripts/random-wallpaper
$HOME/.scripts/setup-details
