#!/bin/bash

if (( $(xrandr --query | grep " connected" | wc -l) > 1)); then
  xrandr --output HDMI-0 --primary
  xrandr --output DVI-D-0 --mode 1440x900 --left-of HDMI-0

  sleep 4
  random-wallpaper
fi

update-datetime
$HOME/.scripts/kblayout us
