#!/bin/bash

if (( $(xrandr --query | grep " connected" | wc -l) > 1)); then
  xrandr --output HDMI-0 --primary
  xrandr --output DP-0 --mode 2560x1440 --rate 170.00 --right-of HDMI-0

  sleep 2
  random-wallpaper
fi

update-datetime
$HOME/.scripts/kblayout us
