#!/bin/sh

if [ $1 = "us" ]; then
    echo "Setting keyboard layout to US International"
    setxkbmap -layout us -variant intl
else
    echo "Setting keyboard layout to BR ABNT2"
    setxkbmap -model abnt2 -layout br -variant abnt2
fi;
