#!/usr/bin/env bash

if (( $(xrandr --query | grep " connected" | wc -l) > 1)); then
  xrandr --output HDMI-0 --primary
  xrandr --output DP-0 --mode 2560x1440 --rate 170.0 --right-of HDMI-0
  xrandr --output DVI-D-0 --mode 1920x1080 --above DP-0

  sleep 2
  random-wallpaper
fi

$HOME/.scripts/kblayout us
xset r rate 250 30
